import { AboutUsIcons, CarDetailsIcons, CarIcon, ChassicNumberIcon, FuelIcon, VehicleInformationIcons } from './CarDetailsIcons';
import {
    CategoryEmptyWalletIcon, CategoryTriangleIcon, HomeScreenAppLogo, AuthScreenHeaderBackground, RightArrow, LeftArrow, CallIcon, ContactIcon, BlogIcon, PackageIcon, AboutUsIcon, SubscriptionIcon, CommentIcon, BlogCalendarIcon, ReferFriendIcon, UserIcon, ProfileIcon, SettingsIcon, LogoutIcon, SearchHistoryIcon, SearchFavouriteIcon, ViewsEyeIcon, BlogShareIcon, CarDetailsHeaderAppIcon, UserPremiumIcon, ContactUsAddressIcon, ContactUsMailIcon, ContactUsCallIcon, WarningGreenIcon, TimerAnalogIcon, ShoppingCartIcon, EnergyIcon, CheckIcon, Cube3Icon, MaxPremiumIcon, DocumentIcon, PremiumProfileIcon, ProfileEditIcon, SettingsSunIcon, SettingsLockIcon, SettingsNotificationIcon, SettingsPasswordSecurityIcon, SettingsProfileIcon, SettingsMySubscriptionIcon, SettingsHelpAndSupportIcon, SettingsTermsAndConditionsIcon, SettingsReportAProblemIcon, SettingsAddOrRemoveAccountIcon, SettingsLogOutIcon, UserProfileCameraIcon, UserProfileCalendarIcon, SettingsRightArrowIcon, SettingsCallIcon, SettingsEmailIcon, SettingsInfoIcon, SettingsOTPClockIcon, SuccessIcon, ErrorIcon, NotificationPopUpIcon, NotificationUpdateIcon, NotificationBlogIcon, NotificationClassifiedIcon, CarBrandIcon, HomeMenuIcon, CarBrandCarIcon, CarBrandSeatIcon, CarBrandFuelTypeHEVIcon, CarBrandFuelTypeELIcon, CarBrandFuelTypeDIcon, CarBrandFuelTypeBIcon, CarBrandFuelTypeCNGIcon, CarBrandFuelTypePHEVIcon, CarBrandYearModelIcon, CarBrandKWIcon, CarBrandAntalCylindrarIcon, CarBrandDriveModelIcon, CarBrandMotorFamiljIcon, CarBrandMotorVolymIcon, CarBranHjuldriftIcon, CarBrandHastkrafterIcon, CarBrandFuelTypeBcon, CarBrandFuelTypeBCNGIcon, CarBrandFuelTypeHBcon, CarBrandFuelTypeHDcon, CarBrandFuelTypeE85con, CarBrandFuelTypeBE85con, CarBrandFuelTypeHIcon, CarBrandFuelTypeLPGcon, CarBrandFuelTypeBLPGcon, LayoutBoxGridUnselectedIcon, LayoutListGridUnselectedIcon, LayoutTextListGridUnselectedIcon, LayoutBoxGridSelectedIcon, LayoutListGridSelectedIcon, LayoutTextListGridSelectedIcon, LayoutTextListLargeGridUnselectedIcon, LayoutTextListLargeGridSelectedIcon, FilterIcon, BusIcon, CabrioletIcon, CoupeIcon, SUVIcon, HalvkombiIcon, SkapbilIcon, GoogleIcon, AppleIcon, BilregistretBannerIconBlack, FacebookIcon, SettingsCookiePolicyIcon, SettingsAnvandarvillkorIcon, FordonTillverkningsmanadIcon, FordonTotalviktIcon, FordonVaxelladaIcon, FordonTjansteviktIcon, trailerCalculatorSuccessCarIcon, trailerCalculatorSuccessCheckIcon, whiteSearchIcon,
    trailerCalculatorCrossIcon,
    trailerCalculatorTrailerIcon,
    trailerCalculatorWarningIcon, bilmarkenYearRangeCalendarIcon,
    UserPremiumIconBlack,
    UserIconBlack, PremiumIconWebHeaderProfile
} from './SvgIcons'

// Images and Icons
export const ImagePath = {
    LoginScreenTopImage: require('../images/LoginScreenHeaderImage.png'),
    BMWImage: require('../images/placeholder.jpeg'),
    placeholder: require('../images/placeholder.jpeg'),
    carIcon: require('../images/SplashIcon.png'),
    userImage: require('../images/ProfileImagePlaceholder.png'),
    emptyImage: require('../images/EmptyImage.png'),
    biluppgifter: require('../images/biluppgifter.webp'),
    bilvardering: require('../images/bilvardering.webp'),
    bilmarken: require('../images/bilmarken.webp'),
    slapvagnskalkylator: require('../images/slapvagnskalkylator.webp'),
    minaFordon: require('../images/mina-fordon.webp'),
    webHeaderHistory: require('../images/web-svg/WebHeaderSVG.svg'),
    webHeaderMinaFordon: require('../images/web-svg/WebMinaFordonSVG.svg'),
    webHeaderJamfora: require('../images/web-svg/WebJamforaSVG.svg'),
    SvgIcons: {
        RightArrow,
        LeftArrow,
        CategoryTriangleIcon,
        CategoryEmptyWalletIcon,
        HomeScreenAppLogo,
        AuthScreenHeaderBackground,
        AboutUsIcon,
        PackageIcon,
        BlogIcon,
        ReferFriendIcon,
        ContactIcon,
        CallIcon,
        SubscriptionIcon,
        CommentIcon,
        BlogCalendarIcon,
        UserIcon,
        UserPremiumIcon,
        ProfileIcon,
        SettingsIcon,
        LogoutIcon,
        SearchHistoryIcon,
        SearchFavouriteIcon,
        ViewsEyeIcon,
        BlogShareIcon,
        CarDetailsHeaderAppIcon,
        CarDetailsIcons,
        ChassicNumberIcon,
        FuelIcon,
        CarIcon,
        VehicleInformationIcons,
        AboutUsIcons,
        ContactUsAddressIcon,
        ContactUsMailIcon,
        ContactUsCallIcon,
        WarningGreenIcon,
        TimerAnalogIcon,
        ShoppingCartIcon,
        EnergyIcon,
        CheckIcon,
        Cube3Icon,
        MaxPremiumIcon,
        DocumentIcon,
        PremiumProfileIcon,
        ProfileEditIcon,
        SettingsProfileIcon,
        SettingsPasswordSecurityIcon,
        SettingsNotificationIcon,
        SettingsLockIcon,
        SettingsSunIcon,
        SettingsMySubscriptionIcon,
        SettingsHelpAndSupportIcon,
        SettingsTermsAndConditionsIcon,
        SettingsReportAProblemIcon,
        SettingsAddOrRemoveAccountIcon,
        SettingsLogOutIcon,
        UserProfileCameraIcon,
        UserProfileCalendarIcon,
        SettingsRightArrowIcon,
        SettingsCallIcon,
        SettingsEmailIcon,
        SettingsInfoIcon,
        SettingsOTPClockIcon,
        SuccessIcon,
        ErrorIcon,
        NotificationPopUpIcon,
        NotificationUpdateIcon,
        NotificationBlogIcon,
        NotificationClassifiedIcon,
        CarBrandIcon,
        CarBrandCarIcon,
        CarBrandSeatIcon,
        CarBrandFuelTypeHEVIcon,
        CarBrandFuelTypeBCNGIcon,
        CarBrandFuelTypeHBcon,
        CarBrandFuelTypeHDcon,
        CarBrandFuelTypeE85con,
        CarBrandFuelTypeBE85con,
        CarBrandFuelTypeHIcon,
        CarBrandFuelTypeLPGcon,
        CarBrandFuelTypeBLPGcon,
        CarBrandFuelTypeELIcon,
        CarBrandFuelTypeDIcon,
        CarBrandFuelTypeCNGIcon,
        CarBrandFuelTypeBIcon,
        CarBrandFuelTypePHEVIcon,
        CarBrandYearModelIcon,
        CarBrandAntalCylindrarIcon,
        CarBrandDriveModelIcon,
        CarBrandMotorFamiljIcon,
        CarBrandKWIcon,
        CarBrandMotorVolymIcon,
        CarBranHjuldriftIcon,
        CarBrandHastkrafterIcon,
        HomeMenuIcon,
        LayoutBoxGridUnselectedIcon,
        LayoutListGridUnselectedIcon,
        LayoutTextListGridUnselectedIcon,
        LayoutBoxGridSelectedIcon,
        LayoutListGridSelectedIcon,
        LayoutTextListGridSelectedIcon,
        LayoutTextListLargeGridUnselectedIcon,
        LayoutTextListLargeGridSelectedIcon,
        FilterIcon,
        BusIcon,
        CabrioletIcon,
        CoupeIcon,
        SUVIcon,
        HalvkombiIcon,
        SkapbilIcon,
        GoogleIcon,
        BilregistretBannerIconBlack,
        FacebookIcon,
        AppleIcon,
        SettingsCookiePolicyIcon,
        SettingsAnvandarvillkorIcon,
        FordonTillverkningsmanadIcon,
        FordonTotalviktIcon,
        FordonVaxelladaIcon,
        FordonTjansteviktIcon,
        trailerCalculatorSuccessCarIcon,
        trailerCalculatorSuccessCheckIcon,
        trailerCalculatorTrailerIcon,
        trailerCalculatorCrossIcon,
        trailerCalculatorWarningIcon,
        whiteSearchIcon,
        bilmarkenYearRangeCalendarIcon,
        UserPremiumIconBlack,
        UserIconBlack,
        PremiumIconWebHeaderProfile,
    }
};

